//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_Email { get; set; }
        public string Acc_Password { get; set; }
        public Nullable<int> Acc_Role { get; set; }
        public string Acc_Mobile { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
