//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clasess
    {
        public int id { get; set; }
        public string Class_Name { get; set; }
        public string Class_Name_ar { get; set; }
        public string Class_title { get; set; }
        public string Class_title_ar { get; set; }
        public string Class_Content { get; set; }
        public string Class_Content_ar { get; set; }
        public string CLass_image { get; set; }
        public Nullable<bool> ClassDisplay { get; set; }

        public List<clasess> clls { get; set; }
        public int CurrentPageIndex { get; set; }
        public int PageCount { get; set; }

    }
}
