//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitnessProfile
    {
        public int FP_ID { get; set; }
        public Nullable<int> Us_ID { get; set; }
        public Nullable<int> MemberShipNo { get; set; }
    
        public virtual User User { get; set; }
    }
}
