//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class glowEntities : DbContext
    {
        public glowEntities()
            : base("name=glowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clasess> clasesses { get; set; }
        public virtual DbSet<offer> offers { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<SLideshow> SLideshows { get; set; }
        public virtual DbSet<Caption> Captions { get; set; }
        public virtual DbSet<FitnessProfile> FitnessProfiles { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PrivateComment> PrivateComments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<branch> branches { get; set; }
    }
}
