//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int Inf_ID { get; set; }
        public int Inf_MembershipNo { get; set; }
        public Nullable<System.DateTime> Inf_Startdate { get; set; }
        public Nullable<System.DateTime> Inf_Enddate { get; set; }
        public Nullable<int> Inf_CaptionName { get; set; }
        public Nullable<int> Inf_FrezzDay { get; set; }
        public Nullable<bool> Inf_Cancel { get; set; }
        public Nullable<bool> Inf_Finished { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
