//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public int id { get; set; }
        public string offername_Ar { get; set; }
        public string offername { get; set; }
        public string offertitle_Ar { get; set; }
        public string offertitle { get; set; }
        public string offercontent_Ar { get; set; }
        public string offercontent { get; set; }
        public string offerImage { get; set; }
        public Nullable<bool> offerDisplay { get; set; }

        public List<offer> offers { get; set; }
        public int CurrentPageIndex { get; set; }
        public int PageCount { get; set; }

    }
}
