//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLideshow
    {
        public int id { get; set; }
        public string slide_Txt { get; set; }
        public string slide_Txt_ar { get; set; }
        public string slide_Slogin { get; set; }
        public string slide_Slogin_ar { get; set; }
        public string slide_Content { get; set; }
        public string slide_Content_ar { get; set; }
        public string slide_Url { get; set; }
        public string slide_image { get; set; }
        public Nullable<bool> SlideDisplay { get; set; }
    }
}
