//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.FitnessProfiles = new HashSet<FitnessProfile>();
            this.PrivateComments = new HashSet<PrivateComment>();
        }
    
        public int Us_Membership { get; set; }
        public string Us_FirstName { get; set; }
        public string Us_LastName { get; set; }
        public string Us_UserName { get; set; }
        public string Us_Password { get; set; }
        public Nullable<int> Us_Mobile { get; set; }
        public string Us_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FitnessProfile> FitnessProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateComment> PrivateComments { get; set; }
    }
}
