//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public int Branch_id { get; set; }
        public string Branch_name { get; set; }
        public string Branch_location { get; set; }
        public string Branch_nameAr { get; set; }
        public string Branch_phone1 { get; set; }
        public string Branch_phone2 { get; set; }
        public string Branch_phone3 { get; set; }
        public string Branch_phone4 { get; set; }
        public string Branch_Whatsapp { get; set; }
        public string Branch_Email { get; set; }
    }
}
