//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int con_id { get; set; }
        public string con_address { get; set; }
        public string Con_Phone { get; set; }
        public string Con_WhatsApp { get; set; }
        public string Con_Email { get; set; }
        public string con_addressAR { get; set; }
    }
}
