//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateComment
    {
        public int PC_ID { get; set; }
        public Nullable<int> PC_CapID { get; set; }
        public string PC_Comment { get; set; }
        public Nullable<int> PC_MembershipNo { get; set; }
    
        public virtual Caption Caption { get; set; }
        public virtual User User { get; set; }
    }
}
