//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glow.Resources.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 282 ElHaram street in front of Cairo mall
        ///Giza.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Addresss {
            get {
                return ResourceManager.GetString("Addresss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGE.
        /// </summary>
        public static string AGE {
            get {
                return ResourceManager.GetString("AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Your BMI.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate BMI.
        /// </summary>
        public static string CalculateYourBMI {
            get {
                return ResourceManager.GetString("CalculateYourBMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Classes_Membership {
            get {
                return ResourceManager.GetString("Classes_Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What You Get From.
        /// </summary>
        public static string CLasses_title1 {
            get {
                return ResourceManager.GetString("CLasses_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have chosen for you the best classes.
        /// </summary>
        public static string CLasses_title2 {
            get {
                return ResourceManager.GetString("CLasses_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string Contact_Information {
            get {
                return ResourceManager.GetString("Contact_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  All rights reserved at .
        /// </summary>
        public static string CopyRIght {
            get {
                return ResourceManager.GetString("CopyRIght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string CopyRIght2 {
            get {
                return ResourceManager.GetString("CopyRIght2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossfit Gym.
        /// </summary>
        public static string CrossfitGym {
            get {
                return ResourceManager.GetString("CrossfitGym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy All The Features.
        /// </summary>
        public static string EnjoyAllTheFeatures {
            get {
                return ResourceManager.GetString("EnjoyAllTheFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have the best sports equipment for the gym (Crossfit - sports equipment - electric treadmills - fitness and accessories. Multi gym - iron devices).
        /// </summary>
        public static string Equipmenttxt {
            get {
                return ResourceManager.GetString("Equipmenttxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLOW GYM.
        /// </summary>
        public static string GLOWGYM {
            get {
                return ResourceManager.GetString("GLOWGYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy food.
        /// </summary>
        public static string Healthyfood {
            get {
                return ResourceManager.GetString("Healthyfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food that causes light food all over the world. And inside to the ideal weight and maintain it..
        /// </summary>
        public static string Healthyfoodtxt {
            get {
                return ResourceManager.GetString("Healthyfoodtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEIGHT.
        /// </summary>
        public static string HEIGHT {
            get {
                return ResourceManager.GetString("HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7.
        /// </summary>
        public static string Hourse {
            get {
                return ResourceManager.GetString("Hourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us.
        /// </summary>
        public static string Joinus {
            get {
                return ResourceManager.GetString("Joinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Plans.
        /// </summary>
        public static string MembershipPlans {
            get {
                return ResourceManager.GetString("MembershipPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 0101 220 8944.
        /// </summary>
        public static string mobNo {
            get {
                return ResourceManager.GetString("mobNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE MONTH.
        /// </summary>
        public static string one_month {
            get {
                return ResourceManager.GetString("one_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE YEAR.
        /// </summary>
        public static string one_Year {
            get {
                return ResourceManager.GetString("one_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hourse :.
        /// </summary>
        public static string OPen {
            get {
                return ResourceManager.GetString("OPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MESSION.
        /// </summary>
        public static string OURMESSION {
            get {
                return ResourceManager.GetString("OURMESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve.
        /// </summary>
        public static string OURMESSION1 {
            get {
                return ResourceManager.GetString("OURMESSION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yourself.
        /// </summary>
        public static string OURMESSION2 {
            get {
                return ResourceManager.GetString("OURMESSION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programe.
        /// </summary>
        public static string Programe {
            get {
                return ResourceManager.GetString("Programe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT BLOG.
        /// </summary>
        public static string RECENTBLOG {
            get {
                return ResourceManager.GetString("RECENTBLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy;.
        /// </summary>
        public static string signCOPyright {
            get {
                return ResourceManager.GetString("signCOPyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREE MONTH.
        /// </summary>
        public static string three_month {
            get {
                return ResourceManager.GetString("three_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Glow Gym. Established in 2019 to help individuals realize their health and fitness goals and reach their full fitness potential. Glow Gym offers a clean and enthusiastic fitness facility evolved into a 1500 square foot with a full range of cardiovascular and strength machines, free weights and also provides a special group exercise classes like step, spinning, yoga, aerobics, zumba, belly dance and indian dance. Our staff and personal trainers are the best at what they offer, depending on experie [rest of string was truncated]&quot;;.
        /// </summary>
        public static string txtabout {
            get {
                return ResourceManager.GetString("txtabout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEIGHT.
        /// </summary>
        public static string WEIGHT {
            get {
                return ResourceManager.GetString("WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string Welcometo {
            get {
                return ResourceManager.GetString("Welcometo", resourceCulture);
            }
        }
    }
}
